server:
  port: 8082
  servlet:
    context-path: /course

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/course_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true