server:
  port: 8084
  servlet:
    context-path: /dkhp

spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/dkhp_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
